name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install package
      run: |
        pip install -e .

    - name: Verify import
      run: |
        python -c "import gtimes; print('✅ GTimes imported successfully')"

    - name: Test basic functionality
      run: |
        python -c "from gtimes.gpstime import gpsFromUTC; week, sow, day, sod = gpsFromUTC(2024, 1, 1, 0, 0, 0); print(f'✅ GPS time: Week {week}, SOW {sow}')"